### ISSUE TITLE
crear una pantalla para analizar las capacidades/necesidades (principalmente para el coordinador) (con filtros, búsqueda, etc)

### ISSUE THREAD

**Issue by sancuba** [emersis-team/emersis#10]
crear una pantalla para analizar las capacidades/necesidades (principalmente para el coordinador) (con filtros, búsqueda, etc)
cada entidad tiene:
nombre
ubicacion
tipo: (hospital, cuartel de bomberos, etc...)
capacidad (nombre de capacidad y cantidad - camas = 100)
necesidad (nombre de necesidad y cantidad - barbijos = 200)

Estructuras de datos al final del documento:
https://docs.google.com/document/d/1TN5y3ZGpvXFCZ9cuucvjGSJJZppWUxv5XsEFn9LeGH0/edit?usp=sharing

**Comment by sancuba** [comment]
cada entidad tiene:
nombre
ubicacion
tipo: (hospital, cuartel de bomberos, etc...)
capacidad (nombre de capacidad y cantidad - camas = 100)
necesidad (nombre de necesidad y cantidad - barbijos = 200)

**Comment by jgarciapolak** [comment]
Del último commit faltan los estilos (a espera del diseño), falta ver como se filtran los datos y como se visualizan

**Comment by sancuba** [comment]
Los bocetos estan en el documento:
https://docs.google.com/document/d/1TN5y3ZGpvXFCZ9cuucvjGSJJZppWUxv5XsEFn9LeGH0/edit#

**Comment by sancuba** [comment]
Terminado
