### ISSUE TITLE
Modelar calcos de ejemplo

### ISSUE THREAD

**Issue by sancuba** [emersis-team/emersis#13]
Modelar calcos de ejemplo:
calco de zonas inundadas
calco de focos de epidemia
etc...

**Comment by pjavier29** [comment]
[Calcos.zip](https://github.com/emersis-team/emersis/files/4411342/Calcos.zip)
3 calco para Emergencia Epidemia (zona con focos de infección con numero de contagiados, otro para ver como aumentó y ver la propagación, otro alguna idea asociada ) -- EN CABA Y GRAN BS AS
3 calcos para Emergencia Inundación (zonas anegadas, centros de evacuación, caminos cortados ) -- EN ENTRE RÍOS
2 calcos para Emergencia Terremoto (Zona afectada por el terremoto, centros de evacuación) -- EN SAN JUAN
